### ISSUE TITLE
Using Transfer to Server

### ISSUE THREAD

**Issue by ALDOlivier31** [cea-sec/usbsas#222]
Hello,

Can you tell me how to transfer the files to a server? What protocol is used, what should be implemented on the remote server, etc.?

Thanks

**Comment by losynix** [comment]
Hello,

The files (archived in a tar) are uploaded with a HTTP POST request on the URL specified in the configuration file, to which is added the identification string, e.g. `http://127.0.0.1/api/uploadbundle/{ID}` (the identification string is always the same for now since the identificator process doesn't do anything).

You can have a look on how this is done in the basic server used for tests: https://github.com/cea-sec/usbsas/blob/main/usbsas-analyzer-server/src/main.rs

**Comment by losynix** [comment]
I'm closing this issue. Feel free to re-open if you have any question.
