### ISSUE TITLE
Installation sur raspberry

### ISSUE THREAD

**Issue by jerGit1** [cea-sec/usbsas#257]
Hello,

Thanks again for the project.
This is not a problem as such but is the project installable on a raspberry?

Looking forward to reading you

**Comment by losynix** [comment]
Hello,

Last time i checked, usbsas builds successfully on ARM architectures so it should work on Raspberry Pi. However, if you intend to deploy a [kiosk](https://github.com/cea-sec/usbsas/blob/main/doc/kiosk.md), you may need to use a different web client than the one used in our documentation ([nwjs](https://nwjs.io/)) because they don't ship ARM builds i'm afraid. We're working on a rust graphical client that would remove the need for a web browser but i can't say when it will be ready.

**Comment by losynix** [comment]
Since we're not using nwjs anymore, usbsas works on raspberry pi (tested on model 4B)
