### ISSUE TITLE
Hid Problem

### ISSUE THREAD

**Issue by Nabil-renault** [cea-sec/usbsas#279]
Hello, I have a few hid problems with the latest version of usbsas (kiosk installation on a debian 12 no desktop env.) : 

- When I boot the machine I first get a debian login screen (where I can't write anything hopefully) and it stays a few seconds before we can see the usbsas interface.
- In the usbsas interface I have an issue with the mouse, such as when I stop moving the mouse even for a a very short time, the mouse goes back to the center of the screen which is problematic as it make difficult to click on button because we usually stop the mouse over them. Sometimes the issue is completely blocking the use of the mouse and unplugging and plugging the mouse again reduce the intensity of the bug but whithout fixing it.

**Comment by losynix** [comment]
Hello,

Regarding your first point, usbsas packages don't handle system hardening or other desirable features for a secure kiosk (like secure boot, disk encryption, hardened and minimal kernel, security modules etc.). That's not their job and not easily doable with packages anyway. We plan to write a guide adressing this but the system hardening is up to you for now.

If you installed the usbsas-hid package, the login screen shouldn't be a problem since USB keyboards aren't supported. You can still disable the login service by first editing `/etc/systemd/logind.conf` like this:
```
[Login]
NAutoVTs=1
ReserveVT=1
```
setting the number to 0 won't work as systemd will still keep the first tty but you can prevent it from spawning by specifically masking it: `# systemctl mask getty@tty1.service`.


As for your second point, I came across this problem on some machines, I'll look into it.

**Comment by Nabil-renault** [comment]
okay, thanks for the answer :)

**Comment by Nabil-renault** [comment]
Hello about the mouse issue, i just saw that the reset of the mouse position on the center of the screen is synchronized with the reset of the animation that we saw in the main screen of usbsas, maybe it will help to identify the origin of the issue

**Comment by losynix** [comment]
I think I found something too, this behavior can happen when multiple HID devices are plugged (mouse, touch screen, keyboard etc.). Also, our HID userspace implementation was mistakenly registering some type of keyboards. That would explain why there is a second cursor always centered since the keyboard doesn't send position updates (that doesn't mean the keyboard would have worked as expected, the program only understands X / Y positions changes, not keyboard keys).

Can you test the latest version ?

**Comment by Nabil-renault** [comment]
It works for me, thank you :)
