### ISSUE TITLE
Read It Twice! A mass-storage-based TOCTTOU attack

### ISSUE THREAD

**Issue by wikijm** [cea-sec/usbsas#6]
Hi everyone,

I loved your [presentation ](https://www.sstic.org/2022/presentation/sasusb_presentation_dun_protocole_sanitaire_pour_lusb/) during SSTIC 2022!

Would you mind sharing the procedure to create a USB drive for exploit the mass-storage-based TOCTTOU attack?
I read carefully the article ['Read It Twice! A mass-storage-based TOCTTOU attack'](https://www.usenix.org/system/files/conference/woot12/woot12-final28.pdf)  and [slides](https://www.usenix.org/sites/default/files/conference/protected-files/michele_woot12_slides.pdf) from Collin Mulliner and Benjamin Michéle without finding anything relevant for that.

My main goal is to do a demo to my colleague and making awareness inside my company about USB attacks.
If you can't or don't want to provide such details publicly, I'll be happy to continue discussion on [Twitter](https://twitter.com/wikijm/).

Also, did you implented a way to protect against
* Such attack on your physical kiosk?
* USB Killer [devices](https://usbkill.com/)?

Regards,
WikiJM

**Comment by serpilliere** [comment]
Oh course we can!
There are plenty of ways to do that:
The device used in the presentation is an AT90UsbKey (which is quite old, http://ww1.microchip.com/downloads/en/devicedoc/doc7627.pdf). We are using the LuFa library (which is quite old http://www.fourwalledcubicle.com/LUFA.php) as UbsMassStorage device ( demo in Demos/Device/ClassDriver/MassStorage) which is a bit modified: for the demo, it stores in the eeprom a bool to store if the next connection will present the flash drive A or B. As the at90usbbey by default has 2 little flash memories (2*8Mo) the code base is modified to show either the first one, or the second one.

Note that this can also be done with other hardware, like RaspberryPI: the goal here is to make it appear as a *device* usb (and not host) and do the same trick to show one or another flash memory.

For the toctou, yes it's protected. In this project:
- the data is first displayed to the user (filename & directories).
- then the user select the wanted files and starts the process
- those files are copied to the local harddrive of the usbsas
- those local datas are then sent to the antivirus (and not re read from the mass storage) 
- the av sends back a json with good/bad files
- the files from the *local* harddrive are filtered and copied to the new usbkey, or sent to the network.

So there is no re read of the data from the usbdrive.
The only *bad* point here is you may have a change of the *metadata* displayed to the user (file name, size,creation date) which are first shown to the user, and then copied to the local drive. We are aware of this but it *might* not be a a problem for the data extraction. By the way, during the data extraction, if a filename has changed, the data read will fail.

For the usb killer, no, there are no protections here: this may not be a problem for our use case: the hardware is cheap (about 250€) and are not in public places.
But maybe you can add a usb hub which will burn instead of the machine?

**Comment by wikijm** [comment]
Hi @serpilliere 

Thanks a lot for those details!

Sorry to ask again, but do you have a project URL to share for using a Raspberry Pi?
Is it something similar to this? https://github.com/wikijm/usbgadget-tool

Regards,
WikiJM

**Comment by serpilliere** [comment]
Hi @wikijm 
Sadly I didn't test with the raspberry pi myself, but I was informed that yes, it's by using usb badged (with this, you can emulate usb devices with the raspberrypi)

**Comment by wikijm** [comment]
Hi @serpilliere

I think I'll try to play with this tutorial: https://magpi.raspberrypi.com/articles/pi-zero-w-smart-usb-flash-drive
I'll close this issue ticket, you already provided to me enough information 😃 

Regards,
WIkiJM
